version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: hsg_redis_cache
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --requirepass "hsg_secret_password" 
      --save 60 1 
      --loglevel warning 
      --maxmemory 200mb 
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "hsg_secret_password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data: